### ISSUE TITLE
Way to call method before screen renders

### ISSUE THREAD

**Issue by panda0603** [musicode/react-native-pure-dimension#1]
Thanks for your module. 

Is there any way to call the methods before component mounts? 

I would like to call the method before screen renders, 

so that I can set the screen height according to the device's height. 

something like below. 

```
const screenHeight = Dimension.getScreenSize();
// just like react native's Dimensions.get('window')
class Main extends Component {
...
}

const styles = StyleSheet.create({
container:{
height: screenHeight
}
})
```
I can't do that right now because it is returning promise. 

Does it have to return promise instead of being syncronized normal function? 

Thanks

**Comment by musicode** [comment]
promise is needed anyway, because js to native is an async call.

**Comment by musicode** [comment]
Call `dimension.getScreenSize()`, you will get the latest screen size.

If you change the device orientation, the size is different.

I hope this can help you.

**Comment by panda0603** [comment]
@musicode  Thanks. 

I'm still not quite sure how I would assign the height directly to stylesheet before component renders for the first time. 

```
const screenHeight = dimension.getScreenSize();
class Main extends Component {
...
}

const styles = StyleSheet.create({
   container:{
       height: screenHeight.height
   }
})
```
above code doesn't work. Can you give me an example?

**Comment by musicode** [comment]
```js
let screenSize = {}
dimension.getScreenSize().then(data => {
   screenSize.width = data.width
   screenSize.height = data.height
})

class App extends Component {
  render() {
     if (isNotReady) {
         return null
     }
     return (
         <View style={{width: screenSize.width, height: screenSize.height}}>

        </View>
     )
  }
}
```

maybe screenSize is not ready when render method is called. so you should make your `App.js` waiting for screenSizee, once promise is resolved, the app is rendered.

**Comment by musicode** [comment]
@panda0603 maybe too late, but the latest version is just what you need.

**Comment by panda0603** [comment]
Perfect, let me give it a try. Will report back if any issues occur. Thanks!
